### ISSUE TITLE
How are the tabular datasets preprocessed?

### ISSUE THREAD

**Issue by BarclayII** [alexis-cvetkov/KEN#1]
First of all, great paper!  I especially found the idea of converting tables to a graph interesting.

I was curious how the tabular data (in particular KDD14 and KDD15) are preprocessed.  I noticed in the paper that you are "using target entities as head entities and linking them to other entries from the same rows".  Does that mean you were only using the single table containing the entities you want to predict, ignoring the other tables?

Thanks!

**Comment by alexis-cvetkov** [comment]
Hi, and thanks for your interest in our work!
Regarding your question, we do convert **all** tables to a graph, not only the single table with the entities of interest.
To that end, we manually select a column in each table, whose entries will be the head entities in the triples of the generated graph.

In practice this column often corresponds to the "main entities" of the table. For instance if I have two tables: one about students and one about courses, I will choose the columns "student" and "course".

Hope that's clear!
